version: '3'
services:
  app:
    container_name: coffee_break_app
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - .:/go/src/coffee-break
    ports:
      - 10080:10080
    depends_on:
      - db
  db:
    container_name: coffee_break_db
    image: mysql:8.0
    # 自動起動の有効化
    restart: always
    # データを永続化させるための設定
    volumes:
      # 初期データを投入するSQLが格納されているdir
      - ./db/mysql_init:/docker-entrypoint-initdb.d
      # 永続化するときにマウントするdir
      - ./db/mysql_data:/var/lib/mysql
    # 環境変数の設定
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TZ}
    ports:
      - ${DB_PORT}:3306
    security_opt:
      - seccomp:unconfined