version: '3'
services:
  app:
    container_name: coffee-break
    build:
      context: docker
      dockerfile: Dockerfile
    volumes:
      - .:/go/src/coffee-break
    ports:
      - 10080:10080
